#!/usr/bin/env bash
# cocon-init.sh - TEE guest initialization script dispatcher
set -euo pipefail

RPATH=$(dirname "${BASH_SOURCE[0]}")

cpu_vendor_id=$(grep -m1 vendor_id /proc/cpuinfo | awk '{printf $3}')

if grep -qw cocoon_no_tee /proc/cmdline;
then
    exec "${RPATH}/cocoon-init-debug" "$@"
fi

if [ "x${cpu_vendor_id}" == "xGenuineIntel" ]
then
    exec ${RPATH}/cocoon-init-tdx "$@"
fi

if [ "x${cpu_vendor_id}" == "xAuthenticAMD" ]
then
    exec ${RPATH}/cocoon-init-sev "$@"
fi

printf "ERR: Unsupported cpu_vendor_id: %s\n" "${cpu_vendor_id}"
exit 1
