[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64
Snapshot=20260408T203914Z

[Content]
Packages=
  linux-image-amd64=6.19.10-1~bpo13+1
  linux-headers-amd64=6.19.10-1~bpo13+1
  systemd
  systemd-timesyncd
  systemd-resolved
  systemd-cryptsetup
  iputils-ping
  jq
  curl
  ca-certificates
  iptables-persistent
  apt
  dbus
  dracut
  cryptsetup
  busybox
  login
  zstd
  liblz4-1
  adduser
  iproute2
  wireguard-tools
  nftables
  kmod
  python3
  pciutils
  procps
  openssl
  less
  git
  xxd

  libfuse3-4
  libarchive13
  libsodium23

  nvidia-persistenced=595.58.03-1
  nvidia-driver-cuda=595.58.03-1
  nvidia-kernel-open-dkms=595.58.03-1
  libcudadebugger1=595.58.03-1
  libnvcuvid1=595.58.03-1
  libnvidia-fbc1=595.58.03-1
  libnvoptix1=595.58.03-1
  libnvidia-encode1=595.58.03-1
  libnvidia-ml1=595.58.03-1
  libnvidia-opticalflow1=595.58.03-1
  libnvidia-present=595.58.03-1
  libnvidia-sandboxutils=595.58.03-1
  libnvidia-tileiras=595.58.03-1
  nvidia-kernel-support=595.58.03-1
  nvidia-opencl-icd=595.58.03-1
  libnvidia-cfg1=595.58.03-1
  libcuda1=595.58.03-1
  libnvidia-nvvm4=595.58.03-1
  libnvidia-nvvm704=595.58.03-1
  nvidia-modprobe=595.58.03-1
  libnvidia-ptxjitcompiler1=595.58.03-1
  libnvidia-pkcs11-openssl3=595.58.03-1
  firmware-nvidia-gsp=595.58.03-1
  libnvidia-gpucomp=595.58.03-1

  /opt/intel/sgx_debian_local_repo/pool/main/s/sgx-dcap-pccs/sgx-dcap-pccs_1.23.100.0-bookworm1+ignorant_amd64.deb
  libtdx-attest
  libsgx-dcap-default-qpl
  libsgx-dcap-quote-verify
  docker.io
  docker-cli
  pipenv
  nvidia-container-toolkit=1.19.0-1
  nvidia-container-toolkit-base=1.19.0-1
  libnvidia-container-tools=1.19.0-1
  libnvidia-container1=1.19.0-1

BuildPackages=
  build-essential
  autoconf
  automake
  autotools-dev
  libtool-bin
  libarchive-dev
  libfuse3-dev
  libboost-dev
  libboost-system-dev
  libboost-thread-dev
  faketime
  git
  ccache
  cmake
  unzip
  tar
  gzip
  unzip
  file
  vim
  zlib1g-dev
  libssl-dev
  liblz4-dev
  libsecp256k1-dev
  gperf
  pkg-config
  libsodium-dev
  libmicrohttpd-dev
  libtdx-attest-dev
  libsgx-enclave-common-dev
  libsgx-dcap-ql-dev
  libsgx-dcap-default-qpl-dev
  libsgx-dcap-quote-verify-dev
  libsgx-launch-dev
  libsgx-tdx-logic-dev


KernelModulesInitrd=no
Bootloader=none

SourceDateEpoch=0
MachineId=04b82d443fe84e459e363be79dfd605f
RemoveFiles=
  /var/log/alternatives.log
  /var/cache/ldconfig/aux-cache

[Validation]
Verity=hash

[Output]
Format=directory
SplitArtifacts=kernel,initrd

[Build]
Incremental=yes
BuildSources=pkg-aux:pkg-aux
BuildSources=pkg-cache:pkg-cache
BuildSources=gpu_attest:gpu_attest
BuildSources=../:cocoon
BuildSources=cocoon-init:cocoon-init
CacheDirectory=./mkosi.cache

ToolsTree=default
ToolsTreeDistribution=debian
ToolsTreeRelease=trixie
ToolsTreePackages=
  cryptsetup
  genimage
  rsync
  python3
